export enum ApiEnvironment {
  Staging = 'staging',
  Production = 'prod',
}


export enum ApplicantTypes {
  PrimaryApplicant = 'PrimaryApplicant',
  CoApplicant = 'CoApplicant'
}

export enum StipulationTypes {
  Income = 'Income',
  ContractCancellationOption = 'ContractCancellationOption',
  Residence = 'Residence',
  PurchaseOrder = 'PurchaseOrder',
  Identity = 'Identity',
  PaidAccount = 'PaidAccount',
  Insurance = 'Insurance',
  Trade = 'Trade',
  Title = 'Title',
  MortgageCurrent = 'MortgageCurrent',
  Registration = 'Registration',
  NonOfficerResolutionRequired = 'NonOfficerResolutionRequired',
  VehicleImages = 'VehicleImages',
  BankruptcyDischarged = 'BankruptcyDischarged',
  CreditApplication = 'CreditApplication',
  NonBureauCredit = 'NonBureauCredit',
  CreditApproval = 'CreditApproval',
  TaxLienSatisfied = 'TaxLienSatisfied',
  CreditScoreDisclosureException = 'CreditScoreDisclosureException',
  ChildSupportPaidAndCurrent = 'ChildSupportPaidAndCurrent',
  RetailInstallmentSalesContract = 'RetailInstallmentSalesContract',
  Rent = 'Rent',
  CosignerNotice = 'CosignerNotice',
  ArticlesOfIncorporation = 'ArticlesOfIncorporation',
  OdometerStatement = 'OdometerStatement',
  ExecutedCrossCollateralDefaultAgreement = 'ExecutedCrossCollateralDefaultAgreement',
  ForeignLanguageAcknowledgement = 'ForeignLanguageAcknowledgement',
  ExecutedGuarantyAgreement = 'ExecutedGuarantyAgreement',
  BookoutSheet = 'BookoutSheet',
  AppearanceProtection = 'AppearanceProtection',
  GapWaiverContract = 'GapWaiverContract',
  BookoutPdf = 'BookoutPdf',
  VehicleServiceContract = 'VehicleServiceContract',
  ContractAddendum = 'ContractAddendum',
  CreditLifeDisabilityContract = 'CreditLifeDisabilityContract',
  CpoCertificate = 'CpoCertificate',
  LienPerfection = 'LienPerfection',
  DisclosureForm = 'DisclosureForm',
  PowerOfAttorney = 'PowerOfAttorney',
  DocFeeDisclosureForm = 'DocFeeDisclosureForm',
  LeaseContract = 'LeaseContract',
  EmergencyRoadsideAssist = 'EmergencyRoadsideAssist',
  PayoffRelease = 'PayoffRelease',
  EmergencyTravelAssist = 'EmergencyTravelAssist',
  AcknowledgementOfRewrittenContract = 'AcknowledgementOfRewrittenContract',
  Etch = 'Etch',
  OrderForm = 'OrderForm',
  ExcessWearAndTear = 'ExcessWearAndTear',
  SSN = 'SSN',
  FaxCoverSheet = 'FaxCoverSheet',
  Phone = 'Phone',
  GapDisclosureAddendum = 'GapDisclosureAddendum',
  AutomaticACHWithdrawal = 'AutomaticACHWithdrawal',
  HailDamageDocument = 'HailDamageDocument',
  Miscellaneous = 'Miscellaneous',
  Invoice = 'Invoice',
  KeyReplacement = 'KeyReplacement',
  ElectronicConsent = 'ElectronicConsent',
  LemonLaw = 'LemonLaw',
  CancellationAgreement = 'CancellationAgreement',
  MailedAaNotice = 'MailedAaNotice',
  ReportOfSale = 'ReportOfSale',
  MaintenanceWorksheet = 'MaintenanceWorksheet',
  CreditReport = 'CreditReport',
  Ofac = 'Ofac',
  GuaranteeOfTitle = 'GuaranteeOfTitle',
  PaintlessDentRepair = 'PaintlessDentRepair',
  AgreementToContact = 'AgreementToContact',
  TheftProtection = 'TheftProtection',
  NegativeEquityForm = 'NegativeEquityForm',
  TheftRecoverySystem = 'TheftRecoverySystem',
  TitleApplication = 'TitleApplication',
  TireWheel = 'TireWheel',
  VerificationOfEmployment = 'VerificationOfEmployment',
  TotalLossProtectionAssurance = 'TotalLossProtectionAssurance'
} 